### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by cassiopaia** [makerdao/maker-market#7] opened 2016-06-28 09:46 UTC
Latest design by @cassiopaia ![bildschirmfoto 2016-05-18 um 18 24 24](https://cloud.githubusercontent.com/assets/620959/15419419/1d0840b0-1e66-11e6-8901-5842c2b0bfdf.png)

**Comment by cassiopaia** [comment] 2016-06-28 09:47
ported from https://github.com/MakerDAO/maker-otc/issues/19

**Comment by pimato** [comment] 2016-07-12 21:47
Hey guys!

I am supporting Cassiopaia on his design work. These are my modified version of his prototype.

**Trading Section:**

![maker_trade](https://cloud.githubusercontent.com/assets/5337809/16784541/7e5899ee-4889-11e6-89b9-8bc525bbe303.png)

- removed the redundant "Available Balance" in the header .
- rearranged every header object to fit the website-padding.
- Allowance balance and normal balance is packed together for every Token of a currency pair. 


**Trading Section:**

![maker_transfer](https://cloud.githubusercontent.com/assets/5337809/16784772/89249b10-488a-11e6-97d2-3c5ea90cee95.png)

- Transfer Papersection added
- History of transfers are now Displayed.

1) what are your thoughts about the changes? 
2) Should we include a timestamp in the transfer history (or maybe every history ? )

Hope to get some feedback so we can improve the prototype to its best!

cheers 
pimato

**Comment by jorisbontje** [comment] 2016-07-13 10:26
@pimato thanks for sharing, some initial feedback:

Trading section:
* The "See All Trades" button should probably be connected to (be part of) the "Last Trades" panel
* I am not sure about having the 2 panels for "New Order" and "Total"; compared to having 2 widgets, 1 for buying and 1 for selling. The latter seems to be a more common pattern for exchanges.
* I would certainly add the timestamps for the last trades visually. Right now we only show them as tooltip, but IMO it should be more obvious when trades happened.
* How / where would I adjust my allowances?
* Other changes look good.

Transfer section:
* The currency pair selection doesn't make sense here; as you select the (single) currency as part of the Transfer widget (ETH dropdown).
* Yeah, I would add timestamps to every history widget.

**Comment by pimato** [comment] 2016-07-14 11:05
Hey Joris and the Team,

Yesterday I sat down and improved my recently presented prototype on the basis of the feedback from Joris and followthechain in our slack channel.

**TRADE SECTION:**

![maker_trade](https://cloud.githubusercontent.com/assets/5337809/16837070/62371ba8-49c1-11e6-9ad1-798fc445656a.png)

**Changes:**

- "See All " Button is now in the "Last Trades" Paper like it should be.
- Timestamp added for the "Last Trades" Paper.
- BUYS / SELLS / MY ORDERS Paper - removed Sum Column.
- BUYS / SELLS / MY ORDERS Paper - Columns changed to PRICE / AMOUNT TOTAL
- BUYS / SELLS / MY ORDERS Paper - changed the colors of the Column Headlines. Description is more important then the Token name (especially if you choose your cryptocurrency pair)
- BUYS / SELLS / MY ORDERS Paper - MY Orders circle indicator added.

**TRANSFER SECTION**

![maker_transfer](https://cloud.githubusercontent.com/assets/5337809/16837234/5a20f29e-49c2-11e6-83e9-2fea58375f24.png)

 **Changes:**

- "See All " Button is now in the "HISTORY" Paper like it should be.
- Timestamp added for the "HISTORY" Paper.


**TODOS:**

**TRADE SECTION**
   - Rethink how someone would want to change the Allowance.
   - Rethink the BUY and SELL Order Papers.
   - option to filter last trades by "my trades".
   
**QUESTION TO THE TEAM**

1. What are your thoughts about the circle indicator in the SELLS and BUYS Paper? The Circle could also change to a remove Icon if the user is moving over his own order.

2. Is it okay if the TRANSFER Paper shows only the half of the Wallet public key ?

cheers 
pimato

**Comment by jorisbontje** [comment] 2016-07-16 18:38
Feedback on Trade section:
* Bid price column header should be "ETH/MKR" rather than "ETH"
* Ask price column header should be "ETH/MKR" rather than "ETH"
*  "Total" and "Amount" don't make sense for the column headers, just make those "MKR" and "ETH".
* The "My Orders" circle indicator makes sense, but then maybe also show them for the "My Orders" panel itself.


Questions:

Q: What are your thoughts about the circle indicator in the SELLS and BUYS Paper? The Circle could also change to a remove Icon if the user is moving over his own order.

A: I wouldn't dual purpose that circle.


Q: Is it okay if the TRANSFER Paper shows only the half of the Wallet public key ?

A: Yes thats okay

**Comment by pimato** [comment] 2016-07-31 20:25
Thanks Joris for your continuous Feedback. 

## TRADE SECTION

![maker_trade](https://cloud.githubusercontent.com/assets/5337809/17279098/1ad9619e-576d-11e6-80cd-c95adddb27bb.png)

# Changes:

- changed price column on BUY and SELL Page to "BID PRICE" and "ASK PRICE"
- Removed "Total" and "Amount" for the column headers,replaced it with simple "MKR" and "ETH".
- Remove-Button added to every order in the "MY ORDER" page.
- complete new redesign of the Order Page.
- separated the New Order Section into BUY and SELL Page.
- BUY and SELL Button added

# Questions:

1) What are your thoughts regarding the new BUY and SELL order pages?

**Comment by jorisbontje** [comment] 2016-08-01 09:49
@pimato I love it. lets build this!

**Comment by cassiopaia** [comment] 2016-08-01 09:50
@pimato : Go ahead! love it as well!

**Comment by dbrock** [comment] 2016-08-08 08:45
Looks beautiful!

Some random thoughts:

* I would spell out the name "Maker Market" below the logo (or somewhere close).
* I would display the word "Morden" in a fully-prominent font color.
* I would display "Contract" and "Account" on separate lines and spell out the complete addresses. I would also change the word "Contract" to "Market".
* I would add some kind of label to clarify what "814.012 MKR" / "565.263 ETH" means.
* I would pick which of "Balance" and "Available" is more important and have only one of them be visually prominent, and put the other one in smaller type below.
* I would spell out "654.432 ETH", "354.321 ETH", "2.153 MKR", "7.876 MKR" (although see previous point) instead of tucking away the symbols off in the corners. I would also use the same font color on both sides.
* Instead of "Currency pair", I would consider using one label on each side: "Currency" vs "Asset".
* I would spell out "Buy orders" and "Sell orders" instead of "Buys" and "Sells". (The latter sounds a little bit like orders that have already been executed.)
* I would get rid of the gray/blue color coding. It's superfluous in the "Buys" and "Sells" sections, so there it can just be removed. At the same time, it's insufficiently clear in the "My orders" section, so there I would instead add a new column called "Type" (with values "Buy" and "Sell").
* In the "History" section, the order type is not as important. I guess that's the one place where I would consider using some kind of color coding, although I would follow established convention and use a pale green and a subtle red to make it more clear what the colors are supposed to signify.
* I would consider changing "History" to "Market history".
* I would consider chopping two or three decimals off all of the numbers. It just seems like visual clutter to show digits representing fractions of a fraction of a penny. The exact amount (with the complete set of decimals) can be put into tool tips.
* I would use a font with tabular figures for all the numbers. https://en.wikipedia.org/wiki/Monospaced_font#Tabular_figures
* Instead of the small circle indicating the user's own orders, I would use a tiny label with the word "YOURS". As a corollary, I would then change the title "My orders" to say "Your orders".

**Comment by pimato** [comment] 2016-08-14 08:45
Hello everyone and thanks to all the feedback. 

It is very important for me to talk about the design, to get a feeling what other people see and think (thanks @dbrock , @jorisbontje ). In the last days I tried to modify my previous design with @dbrock 's feedback. This is the result.

## TRADING SECTION
![maker_trade](https://cloud.githubusercontent.com/assets/5337809/17648087/cddde692-6209-11e6-98a7-c13a692a368e.png)

### CHANGES:

- added the name "Maker Market" below the logo.
- changed the word "Morden" in a fully-prominent font color.
- "Contract" and "Account" dropdown are now on separate lines and spell out the complete addresses.
- changed the "Contract" to "Market" .
- added a label to clarify what "814.012 MKR" / "565.263 ETH" means on the header dashboard.
- headlines "Buys/Sells" changed to "Buy orders/Sell orders"
- added a new column called "Type" (with values "Buy" and "Sell").
- changed "history" to "market history".
- chopped three decimals off all of the numbers.
- added a font with tabular figures for all the numbers.
- allowance balance is now more visually prominent because it is more important then the normal balance. The normal balance is in a smaller type below.
- integrated a button below the token balance to change the allowance of this token.


The Important change is the way we are showing the balance of each token pair.

### Prior:

![bildschirmfoto 2016-08-14 um 10 38 06](https://cloud.githubusercontent.com/assets/5337809/17648119/3cc297f0-620b-11e6-9e03-a0edbbb64673.png)

### After:

![bildschirmfoto 2016-08-14 um 10 36 34](https://cloud.githubusercontent.com/assets/5337809/17648120/42d5d292-620b-11e6-9db0-97ab4e7dbc0d.png)


### Questions:

What are your thoughts regarding the displaying of the Balances?

**Comment by dbrock** [comment] 2016-08-14 12:42
I think it looks great. :+1: 

Maybe we shouldn't display the "total balance" at all, but instead explain all that complicated stuff in the popup that comes up when you click the button (which could say something like "add / remove funds").

And how about making it so that the app always approves infinite allowance for the market, so that we can completely remove from the UI all traces of the concept of "allowance"? (Sorry if this has already been discussed.)

**Comment by kennyrowe** [comment] 2016-08-14 14:54
I agree this is looking really great.

I'm assuming the process for making a trade hasn't changed? If so I think a major challenge of this app is knowing what to do once you have decided you want to make a trade.

The steps of creating an allowance, and then making a deposit before you can make a trade, are not intuitive.

Once the design is in a functional state I would be happy to record my thoughts out loud in a video. That might help hone in any confusions or pain point in the UX.

**Comment by nmushegian** [comment] 2016-08-14 17:06
what about just a little info banner with a gentle pay-attention color with the words "You need to grant the market contract a token allowance. Your Ether must be in the form of ETH Tokens." With links that jump to relevent widgets and goes away when satisfied

**Comment by pimato** [comment] 2016-08-28 12:09
Hey everyone,

I just wanted to push a small update, about my design work for the maker market. In the last days I worked on the buy/sell popup, which appears when you click on a buy or sell order in the tradesection.

![buy_order_popup](https://cloud.githubusercontent.com/assets/5337809/18033540/4a30a8dc-6d28-11e6-9637-110a47ebc884.png)


**Questions:**

1. Should the font of the informationbox (This Action... blabla) be bigger ?
2. Should the minimized version display a little bit more informations ?
3. Should the popup be bigger?

cheers,
geronimo

**Comment by ferni** [comment] 2016-08-29 09:06
Hi, I'm new, I'll probably put a pic on my profile portrait soon.

I agree with @dbrock and @kennyrowe that the process of giving allowance is not very intuitive. I think it's a given that if you're depositing eth into the dapp, you're giving the dapp allowance. So skip the allowance part altogether. If the user is depositing eth, he/she is already signaling that is trusting the dapp with his/her money.

**Comment by nmushegian** [comment] 2016-08-29 17:17
> I agree with @dbrock and @kennyrowe that the process of giving allowance is not very intuitive. I think it's a given that if you're depositing eth into the dapp, you're giving the dapp allowance. So skip the allowance part altogether. If the user is depositing eth, he/she is already signaling that is trusting the dapp with his/her money.

The problem is that this isn't how the token standard works - there is no "approveAndCall" or similar in the current/standard entrypoint.

I find the UX of having two approve 2 transactions after clicking 1 button to be downright terrifying.

**Comment by pimato** [comment] 2016-08-29 17:25
@nmushegian 

could you imagine that those kind of "approveAndCall" methode will be implemented in the future? Or is this against security ?

I tested the token-auction without setting any allowance. Why does it work there and why does it not work on maker market ?

**Comment by nmushegian** [comment] 2016-08-29 21:26
@pimato that doesn't make sense, are you sure you had no allowance? Which token did you use?

**Comment by freekp** [comment] 2016-08-29 21:51
@pimato are you talking about the weekly-mkr-auction frontend, when you mention token-auction? Because there we set the allowance automatically based on the bid that you do on an auction. 

Joris and me thought that would make things a bit more user friendly and we also want to gather feedback about setting the allowance this way instead of separately as on maker-market.

**Comment by pimato** [comment] 2016-08-30 09:40
@freekp , @nmushegian 

yeah I meant the weekly-mkr-auction.

**Comment by pimato** [comment] 2016-09-07 16:35
Hey everyone,
Just made some small changes for the buy/sell offer pupup.

![buy_offer](https://cloud.githubusercontent.com/assets/5337809/18320369/cf26a74a-7529-11e6-82bd-822ef338ef21.png)


#Changes

- Bigger Fontsize.
- Minimized Warning text has now more informationen.

**Comment by pimato** [comment] 2016-09-11 11:11
Heyho,

I just finished the design for the trading section on mkr.market .

## Changes:

### Market closing time added:

- Closed

![bildschirmfoto 2016-09-11 um 13 08 14](https://cloud.githubusercontent.com/assets/5337809/18416846/d80e1aba-7820-11e6-8d9d-5793aa6b766c.png)

- Opened:

![bildschirmfoto 2016-09-11 um 13 09 20](https://cloud.githubusercontent.com/assets/5337809/18416849/f95becd8-7820-11e6-9e53-45e2d0c3c427.png)

### Warning and Update Informations:

![bildschirmfoto 2016-09-11 um 13 10 01](https://cloud.githubusercontent.com/assets/5337809/18416856/134feb26-7821-11e6-9b02-1660d65a723c.png)


## complete Page:

![maker_trade copy](https://cloud.githubusercontent.com/assets/5337809/18416860/309ec88c-7821-11e6-9b94-2ad643707e1f.png)

**Comment by dbrock** [comment] 2016-09-11 11:33
Looking good!

So... sorry if this is going in circles but why are we color-matching "MKR balance" with sell orders and "ETH balance" with buy orders?

One super-minor thing: can we bump up the opacity on the word "volume" at the top? Or I think you could just put it next to the words "ETH" and "MKR" and have it be the same color and font. Also maybe put just a tiny bit more space above "closing time" (that time widget looks great btw)

**Comment by pimato** [comment] 2016-09-11 12:25
Hey Daniel, big thanks for your feedback.

## Changes

- Matching colors with token types (Volume interface with balance)
- Matching colors with buy/sell orders
- opacity on the word "volume" bumped up!
- spacing added between connection information and Market Situation/Closing Time.

![maker_trade copy 2](https://cloud.githubusercontent.com/assets/5337809/18417292/9fd55eaa-782b-11e6-9c02-d4b79b56bbbc.png)

**Closed** 2016-10-13 23:41 UTC
Labels: help wanted
